export const CHANGE_DATE = "CHANGE_DATE";
export const NEXT_DATE = "NEXT_DATE";
export const PREV_DATE = "PREV_DATE";
export const ADD_CLIENT_REQUEST = "ADD_CLIENT_REQUEST";
export const ADD_NEW_RECORD = "ADD_NEW_RECORD";
export const CREATE_NEW_RECORD = "CREATE_NEW_RECORD";
export const EDIT_RECORD = "EDIT_RECORD";
export const DELET_RECORD = "DELET_RECORD";
export const CREATE_NEW_SERVICE = "CREATE_NEW_SERVICE";
export const EDIT_CLIENT = "EDIT_CLIENT";
export const DELET_CLIENT = "DELET_CLIENT";

// get clients
export const CLIENTS_REQUEST = "CLIENT_REQUEST";
export const CLIENTS_REQUEST_SUCCESS = "CLIENTS_REQUEST_SUCCESS";
export const CLIENTS_REQUEST_FAIL = "CLIENTS_REQUEST_FAIL";

//

export const ADD_CLIENT_SUCCESS = "ADD_CLIENT_SUCCESS";
export const CLIENT_ADD_FAIL = "CLIENT_ADD_FAIL";
export const ADD_CLIENT = "ADD_CLIENT";
// delet client
export const DELET_CLIENT_REQUEST = "DELET_CLIENT_REQUEST";
export const DELET_CLIENT_SUCCESS = "DELET_CLIENT_SUCCESS";
export const CLIENT_DELET_FAIL = "CLIENT_DELET_FAIL";
export const CLEAR_ERROR_DELET_FAIL = "CLEAR_ERROR_DELET_FAIL";
export const CLEAR_ERROR_REQUEST_FAIL = "CLEAR_ERROR_REQUEST_FAIL";
export const CLEAR_ERROR_CLIENT_ADD_FAIL = "CLEAR_ERROR_CLIENT_ADD_FAIL";

export const EDIT_CLIENT_REQUEST = "EDIT_CLIENT_REQUEST";
export const EDIT_CLIENT_SUCCESS = "EDIT_CLIENT_SUCCESS";
export const EDIT_CLIENT_FAIL = "EDIT_CLIENT_FAIL;";
export const CLEAR_ERROR_EDIT_FAIL = "CLEAR_ERROR_EDIT_FAIL";
