export const CHANGE_DATE = "CHANGE_DATE";
export const NEXT_DATE = "NEXT_DATE";
export const PREV_DATE = "PREV_DATE";
export const ADD_CLIENT_REQUEST = "ADD_CLIENT_REQUEST";
export const ADD_NEW_RECORD = "ADD_NEW_RECORD";
export const CREATE_NEW_RECORD = "CREATE_NEW_RECORD";
export const EDIT_RECORD = "EDIT_RECORD";
export const DELET_RECORD = "DELET_RECORD";
export const CREATE_NEW_SERVICE = "CREATE_NEW_SERVICE";
export const EDIT_CLIENT = "EDIT_CLIENT";
export const DELET_CLIENT = "DELET_CLIENT";

//Categories

// Category add
export const ADD_CATEGORY = "ADD_CATEGORY";
export const ADD_SERVICE_CATEGORY_REQUEST = "ADD_SERVICE_CATEGORY_REQUEST";
export const ADD_SERVICE_CATEGORY_SUCCESS = "ADD_SERVICE_CATEGORY_SUCCESS";
export const CLEAR_MESSAGE_CATEGORY_ADD_SUCCESS = "CLEAR_MESSAGE_CATEGORY_ADD_SUCCESS";
export const SERVICE_CATEGORY_ADD_FAIL = "SERVICE_CATEGORY_ADD_FAIL";
export const CLEAR_SERVICE_CATEGORY_ADD_FAIL = "CLEAR_SERVICE_CATEGORY_ADD_FAIL";

// get
export const CATEGORY_PAGE_REQUEST = "CATEGORY_PAGE_REQUEST";
export const GET_CATEGORIES_REQUEST = "GET_CATEGORIES_REQUEST";
export const GET_CATEGORIES_REQUEST_SUCCESS = "GET_CATEGORIES_REQUEST_SUCCESS";
export const GET_CATEGORIES_REQUEST_FAIL = "GET_CATEGORIES_REQUEST_FAIL";
export const CLEAR_ERROR_GET_CATEGORIES_REQUEST_FAIL = "CLEAR_ERROR_GET_CATEGORIES_REQUEST_FAIL";

// edit
export const EDIT_CATEGORY = "EDIT_CATEGORY";
export const EDIT_CATEGORY_REQUEST = "EDIT_CATEGORY_REQUEST";
export const EDIT_CATEGORY_SUCCESS = "EDIT_CATEGORY_SUCCESS";
export const CLEAR_MESSAGE_CATEGORY_EDIT_SUCCESS = "CLEAR_MESSAGE_CATEGORY_EDIT_SUCCESS";
export const EDIT_CATEGORY_FAIL = "EDIT_CATEGORY_FAIL";
export const CLEAR_MESSAGE_CATEGORY_EDIT_FAIL = "CLEAR_MESSAGE_CATEGORY_EDIT_FAIL";

// delet
export const DELET_CATEGORY = "DELET_CATEGORY";
export const DELET_CATEGORY_REQUEST = "DELET_CATEGORY_REQUEST";
export const DELET_CATEGORY_SUCCESS = "DELET_CATEGORY_SUCCESS";
export const CLEAR_MESSAGE_CATEGORY_DELET_SUCCESS = "CLEAR_MESSAGE_CATEGORY_DELET_SUCCESS";
export const DELET_CATEGORY_FAIL = "DELET_CATEGORY_FAIL";
export const CLEAR_MESSAGE_CATEGORY_DELET_FAIL = "CLEAR_MESSAGE_CATEGORY_DELET_FAIL";

// Colors

export const COLORS_REQUEST = "COLORS_REQUEST";
export const COLORS_REQUEST_SUCCESS = "COLORS_REQUEST_SUCCESS";
export const COLORS_REQUEST_FAIL = "COLORS_REQUEST_FAIL";
export const CLEAR_ERROR_REQUEST_COLORS_FAIL = "CLEAR_ERROR_REQUEST_COLORS_FAIL";

// Services

//services get
export const GET_SERVICES_REQUEST = "GET_SERVICES_REQUEST";
export const GET_SERVICES_REQUEST_SUCCESS = "GET_SERVICES_REQUEST_SUCCESS";
export const GET_SERVICES_REQUEST_FAIL = "GET_SERVICES_REQUEST_FAIL";
export const CLEAR_ERROR_GET_SERVICES_REQUEST_FAIL = "CLEAR_ERROR_GET_SERVICES_REQUEST_FAIL";

// services add
export const ADD_SERVIC = "ADD_SERVIC";
export const ADD_SERVIC_REQUEST = "ADD_SERVIC_REQUEST";
export const ADD_SERVIC_SUCCESS = "ADD_SERVICE_SUCCESS";
export const ADD_SERVIC_FAIL = "ADD_SERVICE_FAIL";
export const CLEAR_MESSAGE_SERVIC_ADD_FAIL = "CLEAR_MESSAGE_SERVIC_ADD_FAIL";
export const CLEAR_MESSAGE_SERVIC_ADD_SUCCESS = "CLEAR_MESSAGE_SERVIC_ADD_SUCCESS";

// services edit
export const EDIT_SERVIC = "EDIT_SERVIC";
export const EDIT_SERVIC_REQUEST = "EDIT_SERVIC_REQUEST";
export const EDIT_SERVIC_SUCCESS = "EDIT_SERVIC_SUCCESS";
export const CLEAR_MESSAGE_SERVIC_EDIT_SUCCESS = "CLEAR_MESSAGE_SERVIC_EDIT_SUCCESS";
export const EDIT_SERVIC_FAIL = "EDIT_SERVIC_FAIL";
export const CLEAR_MESSAGE_SERVIC_EDIT_FAIL = "CLEAR_MESSAGE_SERVIC_EDIT_FAIL";

// services delet
export const DELET_SERVICE = "DELET_SERVICE";
export const DELET_SERVIC_REQUEST = "DELET_SERVIC_REQUEST";
export const DELET_SERVIC_SUCCESS = "DELET_SERVIC_SUCCESS";
export const CLEAR_MESSAGE_SERVIC_DELET_SUCCESS = "CLEAR_MESSAGE_SERVIC_DELET_SUCCESS";
export const DELET_SERVIC_FAIL = "DELET_SERVIC_FAIL";
export const CLEAR_MESSAGE_SERVIC_DELET_FAIL = "CLEAR_MESSAGE_SERVIC_DELET_FAIL";

// Service page
export const SERVICE_PAGE_REQUEST = "SERVICE_PAGE_REQUEST";
export const GET_SERVICES_AND_CATEGORIES_REQUEST_SUCCESS = "GET_SERVICES_AND_CATEGORIES_REQUEST_SUCCESS";
export const GET_SERVICES_AND_CATEGORIES_REQUEST_ERROR = "GET_SERVICES_AND_CATEGORIES_REQUEST_ERROR";

export const CLEAR_ERROR_REQUEST_FAIL = "CLEAR_ERROR_REQUEST_FAIL";
